### ISSUE TITLE
Ability to enlarge card text

### ISSUE THREAD

**Issue by sparetomato** [shafeen/swdestinystation-task-board#15] opened 2018-06-05 12:27 UTC
on a smaller laptop it is sometimes hard to read the card text to check what it does. Could you make a way of enlarging the card text please?

**Comment by shafeen** [comment] 2018-06-05 13:38
Duplicate of #6.

**Comment by sparetomato** [comment] 2018-06-05 14:12
Sorry, didn't see #6 in the list

**Closed as completed** 2018-06-05 14:11 UTC
Labels: duplicate
